### PR TITLE
Add mame-essentials as package

### PR DESCRIPTION
**Pull request by mmicko**

### CODE REVIEW

**Comment by cuavas** [comment]
Why does this have a `make` binary in it?  I’d like to avoid having anything that conflicts with regular MSYS64 tools.

What’s the purpose of the empty init.sh file?  You could use `bash --login /dev/null` or `bash --login <(true)` to execute an empty script without needing a confusing empty file.

To minimise binary blobs, it would be better to add a dependency on `p7zip` package (from `msys` repo), not include the 7za.exe executable, and install the 7z.sfx file in `/usr/lib/p7zip` so the MSYS64 7za tool will find it.

Several scripts are missing the newline on the final line.

Is calling the directory where the miscellaneous MAME stuff goes `/win32` really the best thing to do?  Can we call it `/opt/mamedev` or something more conventional?

**Comment by cuavas** [comment]
Given I have MSYS instances from a regular installation and git for Windows, how would I make an additional clean msys64 instance for testing purposes?  I don’t want to run the installer again, as it creates start menu items etc. and would likely interfere with my existing msys64 instance.  Is there a package that creates a self-contained MSYS instance without messing with start menu, registry, etc.?

**Comment by mmicko** [comment]
Hi, I did not change any of scripts we used in previous builds so that is reason for location, missing newline at end of file and similar.
Reason why make.exe is there is that if you are using make.exe from msys2 then you are in posix environment, and with this modified make you can run in plain windows environment. Since we override path we are using this in non-posix environment.
For 7zip guess we can fix that and make old build scripts work without any change.

Regarding msys package that does not mess with start menu and registry, think there is no such thing. Best you can do is install it on VM and zip content of installed directory to place on new machine.

**Comment by mmicko** [comment]
Note one thing. All binaries and scripts in package are ONLY for non-posix compilation, so out of msys2 environment (since that is what win32 users are get used to use)

**Comment by mmicko** [comment]
All mentioned issues have been addressed.

**Pull request merged**
